In [2]:
import numpy as np


def generate_random_numbers(size, min_val, max_val):
    return np.random.randint(min_val, max_val, size)


random_numbers = generate_random_numbers(50, 1, 1777700)
print(random_numbers)
# python array
python_arr = [1, 3, 4, 5]
# convert to numpy array
numpy_arr = np.array(python_arr)
print(numpy_arr)
print(type(numpy_arr))

[1337162  268620  351947 1756409  920778 1257826 1212848  777715  435675
  391294 1232389  567544  388478  202497  773840 1392457  113209  516721
 1697984 1170976 1074339  435798  242726  555971 1442958 1708005  912953
 1242509  201671 1491604  441336  431970  617961 1403614 1404959  415888
  450751  891709   28970  779270 1762187 1761792 1283470  839433 1359369
 1368635 1508346 1456745  448025 1738417]
[1 3 4 5]
<class 'numpy.ndarray'>


In [3]:

# numpy array operations
numpy_arr_2 = np.array([1, 2, 3, 4, 5])
print("numpy_arr_2:", numpy_arr_2)
print("numpy_arr_2 + 2:", numpy_arr_2 + 2)
print("numpy_arr_2 * 2:", numpy_arr_2 * 2)
print("numpy_arr_2 / 2:", numpy_arr_2 / 2)
print("numpy_arr_2 ** 2:", numpy_arr_2 ** 2)
print("numpy_arr_2.sum():", numpy_arr_2.sum())

numpy_arr_2: [1 2 3 4 5]
numpy_arr_2 + 2: [3 4 5 6 7]
numpy_arr_2 * 2: [ 2  4  6  8 10]
numpy_arr_2 / 2: [0.5 1.  1.5 2.  2.5]
numpy_arr_2 ** 2: [ 1  4  9 16 25]
numpy_arr_2.sum(): 15


In [4]:
print("numpy_arr_2.mean():", numpy_arr_2.mean())
print("numpy_arr_2.std():", numpy_arr_2.std())

numpy_arr_2.mean(): 3.0
numpy_arr_2.std(): 1.4142135623730951


In [5]:
import time

python_2d_arr = [[1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6], [1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                                                                                                                                                              6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6], [1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6]]
start_python_time = time.time()
python_2d_arr_sum = sum([sum(row) for row in python_2d_arr])
end_python_time = time.time()
print("Python 2D array sum:", python_2d_arr_sum,
      " total time taken:", end_python_time-start_python_time)

# lets do the same with numpy
numpy_2d_arr = np.array(python_2d_arr)
start_numpy_time = time.time()
numpy_2d_arr_sum = numpy_2d_arr.sum()
end_numpy_time = time.time()
print("Numpy 2D array sum:", numpy_2d_arr_sum,
      " total time taken:", end_numpy_time-start_numpy_time)

Python 2D array sum: 1320  total time taken: 3.409385681152344e-05
Numpy 2D array sum: 1320  total time taken: 3.790855407714844e-05


In [6]:
numpy_arr_2 = np.array([1, 2, 3, 4, 5, 6])
print("numpy_arr_2:", numpy_arr_2)
# shape method - returns the dimensions of the array as a tuple
print("numpy_arr_2.shape:", numpy_arr_2.shape)
numpy_2d_arr_3x3 = np.random.randint(1, 11, size=(4, 4))
print("numpy_2d_arr_3x3:", numpy_2d_arr_3x3)
"""
reshape()- returns a new array with the specified shape.
input parameters:
- newshape: a tuple of integers defining the new shape.
   - eg, (2,3)- the array will be reshaped to a 2x3 array.
   - 3g (2,3,4)- the array will be reshaped to a 2x3x4 array.
- (t1,t12,t3,t4)
   """
print("numpy_2d_arr_3x3m-reshape ----", numpy_2d_arr_3x3.shape,
      numpy_2d_arr_3x3.reshape(4, 2, 2), "-----")

# get the maximum value in the array
print("numpy_2d_arr_3x3.max():", numpy_2d_arr_3x3.max())
# get the minimum value in the array
print("numpy_2d_arr_3x3.min():", numpy_2d_arr_3x3.shape, numpy_2d_arr_3x3.min())

# retrun all element as array or flatted array
# print("numpy_2d_arr_3x3.flatten():",numpy_2d_arr_3x3.flatten())
# reshape the array
# print("numpy_2d_arr_3x3.reshape(4,16):",numpy_2d_arr_3x3.reshape(4,16))
# print(numpy_2d_arr_3x3)

# type of numpy array
print(type(numpy_2d_arr_3x3), "items types", numpy_2d_arr_3x3.dtype)
# cast the all items to float/anything
print("numpy_2d_arr_3x3.astype(float):", numpy_2d_arr_3x3.astype(float))

numpy_arr_2: [1 2 3 4 5 6]
numpy_arr_2.shape: (6,)
numpy_2d_arr_3x3: [[ 3  4  4  5]
 [ 3  6 10  9]
 [ 4  9  8  2]
 [ 8  8  6  6]]
numpy_2d_arr_3x3m-reshape ---- (4, 4) [[[ 3  4]
  [ 4  5]]

 [[ 3  6]
  [10  9]]

 [[ 4  9]
  [ 8  2]]

 [[ 8  8]
  [ 6  6]]] -----
numpy_2d_arr_3x3.max(): 10
numpy_2d_arr_3x3.min(): (4, 4) 2
<class 'numpy.ndarray'> items types int64
numpy_2d_arr_3x3.astype(float): [[ 3.  4.  4.  5.]
 [ 3.  6. 10.  9.]
 [ 4.  9.  8.  2.]
 [ 8.  8.  6.  6.]]


In [7]:
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])
# merge two arrays
print("np.concatenate((np_arr1, np_arr2)):",
      np.concatenate((np_arr1, np_arr2)))
# other way to merge two arrays
print("np.hstack((np_arr1, np_arr2)):", np.hstack((np_arr1, np_arr2)))
print("np.vstack((np_arr1, np_arr2)):", np.vstack((np_arr1, np_arr2)))

np.concatenate((np_arr1, np_arr2)): [ 1  2  3  4  5  6  7  8  9 10]
np.hstack((np_arr1, np_arr2)): [ 1  2  3  4  5  6  7  8  9 10]
np.vstack((np_arr1, np_arr2)): [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
my_numpy_arr = np.array([32, 3, 2, 4, 5, 5, 34, 34]).reshape(2, 2, 2)
print("my_numpy_arr:", my_numpy_arr)

my_numpy_arr: [[[32  3]
  [ 2  4]]

 [[ 5  5]
  [34 34]]]


In [9]:
np_arr = np.random.randint(10, 70, size=(5, 5))

In [10]:
print("np_arr:", np_arr)

np_arr: [[17 34 63 43 61]
 [20 20 52 53 42]
 [40 23 53 10 49]
 [31 18 56 63 33]
 [51 11 63 62 49]]


In [11]:
np_arr_flattened = np_arr.flatten()
print("np_arr_flattened:", np_arr_flattened)

np_arr_flattened: [17 34 63 43 61 20 20 52 53 42 40 23 53 10 49 31 18 56 63 33 51 11 63 62
 49]


In [12]:
np_arr_sorted = np.sort(np_arr)
# by default np sorting in ascending order
print("np_arr_sorted:", np_arr_sorted)
# to sort in descending order we can use
print("np_arr_sorted_descending:", np.sort(np_arr, axis=0)[::-1])
# or
print("np_arr_sorted_descending:", np.sort(np_arr, kind="mergesort"))
# [::-1] is used to reverse the sorted order, achieving descending sorting


# create a random 5x5 matrix
np_arr_rand = np.random.rand(5, 5)
print("np_arr_rand: 5*5", np_arr_rand)
# calculate the sum of all elements in the matrix
print("np_arr_rand.sum():", np_arr_rand.sum())
# calculate the mean of all elements in the matrix
print("np_arr_rand.mean():", np_arr_rand.mean())
# calculate the standard deviation of all elements in the matrix
print("np_arr_rand.std():", np_arr_rand.std())


# we can also do metrix operations using numpy
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])

np_arr_sorted: [[17 34 43 61 63]
 [20 20 42 52 53]
 [10 23 40 49 53]
 [18 31 33 56 63]
 [11 49 51 62 63]]
np_arr_sorted_descending: [[51 34 63 63 61]
 [40 23 63 62 49]
 [31 20 56 53 49]
 [20 18 53 43 42]
 [17 11 52 10 33]]
np_arr_sorted_descending: [[17 34 43 61 63]
 [20 20 42 52 53]
 [10 23 40 49 53]
 [18 31 33 56 63]
 [11 49 51 62 63]]
np_arr_rand: 5*5 [[0.90497985 0.56233748 0.68317913 0.894031   0.52336295]
 [0.70917431 0.72923325 0.08544737 0.34515177 0.58261584]
 [0.96249034 0.63170033 0.74372235 0.12227796 0.3704829 ]
 [0.8887675  0.37029924 0.60923791 0.90886236 0.59285403]
 [0.99238637 0.79175778 0.12796697 0.61579038 0.56599577]]
np_arr_rand.sum(): 15.314105133755476
np_arr_rand.mean(): 0.612564205350219
np_arr_rand.std(): 0.2552616328613155


In [13]:
# we can also do metrix operations using numpy
np_arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [2, 3, 4, 5]])
np_arr2 = np.array([[-1, 2.3, 3, 4], [-5, 6.7, 8, 9], [1, 2, 3, 4]])

# add two arrays
print("np_arr1 + np_arr2:", np_arr1 + np_arr2)
# subtract two arrays
print("np_arr1 - np_arr2:", np_arr1 - np_arr2)
# multiply two arrays
print("np_arr1 * np_arr2:", np_arr1 * np_arr2)
# divide two arrays
print("np_arr1 / np_arr2:", np_arr1 / np_arr2)

print("np_arr1:", np.array(np_arr1, dtype=np.float64))

np_arr1 + np_arr2: [[ 0.   4.3  6.   8. ]
 [ 0.  12.7 15.  17. ]
 [ 3.   5.   7.   9. ]]
np_arr1 - np_arr2: [[ 2.  -0.3  0.   0. ]
 [10.  -0.7 -1.  -1. ]
 [ 1.   1.   1.   1. ]]
np_arr1 * np_arr2: [[ -1.    4.6   9.   16. ]
 [-25.   40.2  56.   72. ]
 [  2.    6.   12.   20. ]]
np_arr1 / np_arr2: [[-1.          0.86956522  1.          1.        ]
 [-1.          0.89552239  0.875       0.88888889]
 [ 2.          1.5         1.33333333  1.25      ]]
np_arr1: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 3. 4. 5.]]


In [14]:
print("Number of axixes:", np_arr1.ndim)
print("Shape of array:", np_arr1.shape)
print("Size of array:", np_arr1.size)
print("Data type of array:", np_arr1.dtype)

Number of axixes: 2
Shape of array: (3, 4)
Size of array: 12
Data type of array: int64


In [15]:
print("Array's memory size:", np_arr1.nbytes)

print("np_arr1:", np.empty((3, 4)))

Array's memory size: 96
np_arr1: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 3. 4. 5.]]


In [16]:
print("ones array:", np.ones((10, 3)))
my_numpy_arr = np.linspace(0, 2.5, 20).reshape(2, 5, 2)
print("my_numpy_arr:", 10*np.sign(my_numpy_arr))

ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
my_numpy_arr: [[[ 0. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]]


In [17]:
print("array with predicated values:", np.linspace(0, 1, 6).reshape(3, 2, 1))

array with predicated values: [[[0. ]
  [0.2]]

 [[0.4]
  [0.6]]

 [[0.8]
  [1. ]]]


In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# matrix multiplication
print("Matrix multiplication of A and B:", A @ B)
print("using numpy multiply function:", np.matmul(A, B))
print("we can also use dot fun from numpy", np.dot(A, B))

# A*B - element-wise multiplication or product
# A-B - element-wise subtraction
# A+B - element-wise addition
# A/B - element-wise division
# A**2 - element-wise square

Matrix multiplication of A and B: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
using numpy multiply function: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
we can also use dot fun from numpy [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [46]:
# universal functions of numpy
# 1. exp() - exponential function
import numpy as np
B = np.arange(5, 10)
print("Matrix B:", B)
# exponential - calculates the exponential of each element in B
print("exp(B):", np.exp(B))
# log() - calculates the natural logarithm (base e) of each element in B
print("log(B):", np.log(B))
# sin() - calculates the sine of each element in B
print("sin(B):", np.sin(B))
# cos() - calculates the cosine of each element in B
print("cos(B):", np.cos(B))

Matrix B: [5 6 7 8 9]
exp(B): [ 148.4131591   403.42879349 1096.63315843 2980.95798704 8103.08392758]
log(B): [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
sin(B): [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
cos(B): [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]


In [92]:

random_arr = np.random.randint(1, int(np.pi), size=(3, 4))
print("Random 3x4 array with pi:", random_arr)

print("\n\n--------")
for row in random_arr:
    print(row)

Random 3x4 array with pi: [[2 2 2 1]
 [1 2 2 2]
 [1 1 2 2]]


--------
[2 2 2 1]
[1 2 2 2]
[1 1 2 2]
