In [2]:
import numpy as np


def generate_random_numbers(size, min_val, max_val):
    return np.random.randint(min_val, max_val, size)


random_numbers = generate_random_numbers(50, 1, 1777700)
print(random_numbers)
# python array
python_arr = [1, 3, 4, 5]
# convert to numpy array
numpy_arr = np.array(python_arr)
print(numpy_arr)
print(type(numpy_arr))

[ 978950 1681940 1057490 1548647 1603543  536714 1301629 1594455  652705
 1571346 1181603   39923  787439 1070636 1678989 1656794  969553  736642
 1074779  201295  260988 1593807  401860 1418605  550387  250254 1182121
  779110  400738  843292  291564  764751 1610185 1341945 1722741 1456278
  827339  162723 1374797  478386 1444622  610576   66549 1327569  336124
 1029892 1193944 1354814  744533 1767052]
[1 3 4 5]
<class 'numpy.ndarray'>


In [3]:

# numpy array operations
numpy_arr_2 = np.array([1, 2, 3, 4, 5])
print("numpy_arr_2:", numpy_arr_2)
print("numpy_arr_2 + 2:", numpy_arr_2 + 2)
print("numpy_arr_2 * 2:", numpy_arr_2 * 2)
print("numpy_arr_2 / 2:", numpy_arr_2 / 2)
print("numpy_arr_2 ** 2:", numpy_arr_2 ** 2)
print("numpy_arr_2.sum():", numpy_arr_2.sum())

numpy_arr_2: [1 2 3 4 5]
numpy_arr_2 + 2: [3 4 5 6 7]
numpy_arr_2 * 2: [ 2  4  6  8 10]
numpy_arr_2 / 2: [0.5 1.  1.5 2.  2.5]
numpy_arr_2 ** 2: [ 1  4  9 16 25]
numpy_arr_2.sum(): 15


In [4]:
print("numpy_arr_2.mean():", numpy_arr_2.mean())
print("numpy_arr_2.std():", numpy_arr_2.std())

numpy_arr_2.mean(): 3.0
numpy_arr_2.std(): 1.4142135623730951


In [5]:
import time

python_2d_arr = [[1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6], [1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                                                                                                                                                              6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6], [1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6]]
start_python_time = time.time()
python_2d_arr_sum = sum([sum(row) for row in python_2d_arr])
end_python_time = time.time()
print("Python 2D array sum:", python_2d_arr_sum,
      " total time taken:", end_python_time-start_python_time)

# lets do the same with numpy
numpy_2d_arr = np.array(python_2d_arr)
start_numpy_time = time.time()
numpy_2d_arr_sum = numpy_2d_arr.sum()
end_numpy_time = time.time()
print("Numpy 2D array sum:", numpy_2d_arr_sum,
      " total time taken:", end_numpy_time-start_numpy_time)

Python 2D array sum: 1320  total time taken: 3.504753112792969e-05
Numpy 2D array sum: 1320  total time taken: 3.2901763916015625e-05


In [6]:
numpy_arr_2 = np.array([1, 2, 3, 4, 5, 6])
print("numpy_arr_2:", numpy_arr_2)
# shape method - returns the dimensions of the array as a tuple
print("numpy_arr_2.shape:", numpy_arr_2.shape)
numpy_2d_arr_3x3 = np.random.randint(1, 11, size=(4, 4))
print("numpy_2d_arr_3x3:", numpy_2d_arr_3x3)
"""
reshape()- returns a new array with the specified shape.
input parameters:
- newshape: a tuple of integers defining the new shape.
   - eg, (2,3)- the array will be reshaped to a 2x3 array.
   - 3g (2,3,4)- the array will be reshaped to a 2x3x4 array.
- (t1,t12,t3,t4)
   """
print("numpy_2d_arr_3x3m-reshape ----", numpy_2d_arr_3x3.shape,
      numpy_2d_arr_3x3.reshape(4, 2, 2), "-----")

# get the maximum value in the array
print("numpy_2d_arr_3x3.max():", numpy_2d_arr_3x3.max())
# get the minimum value in the array
print("numpy_2d_arr_3x3.min():", numpy_2d_arr_3x3.shape, numpy_2d_arr_3x3.min())

# retrun all element as array or flatted array
# print("numpy_2d_arr_3x3.flatten():",numpy_2d_arr_3x3.flatten())
# reshape the array
# print("numpy_2d_arr_3x3.reshape(4,16):",numpy_2d_arr_3x3.reshape(4,16))
# print(numpy_2d_arr_3x3)

# type of numpy array
print(type(numpy_2d_arr_3x3), "items types", numpy_2d_arr_3x3.dtype)
# cast the all items to float/anything
print("numpy_2d_arr_3x3.astype(float):", numpy_2d_arr_3x3.astype(float))

numpy_arr_2: [1 2 3 4 5 6]
numpy_arr_2.shape: (6,)
numpy_2d_arr_3x3: [[ 1 10  8  3]
 [ 2  6  6  1]
 [ 9  9  2  8]
 [ 4 10  4  4]]
numpy_2d_arr_3x3m-reshape ---- (4, 4) [[[ 1 10]
  [ 8  3]]

 [[ 2  6]
  [ 6  1]]

 [[ 9  9]
  [ 2  8]]

 [[ 4 10]
  [ 4  4]]] -----
numpy_2d_arr_3x3.max(): 10
numpy_2d_arr_3x3.min(): (4, 4) 1
<class 'numpy.ndarray'> items types int64
numpy_2d_arr_3x3.astype(float): [[ 1. 10.  8.  3.]
 [ 2.  6.  6.  1.]
 [ 9.  9.  2.  8.]
 [ 4. 10.  4.  4.]]


In [7]:
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])
# merge two arrays
print("np.concatenate((np_arr1, np_arr2)):",
      np.concatenate((np_arr1, np_arr2)))
# other way to merge two arrays
print("np.hstack((np_arr1, np_arr2)):", np.hstack((np_arr1, np_arr2)))
print("np.vstack((np_arr1, np_arr2)):", np.vstack((np_arr1, np_arr2)))

np.concatenate((np_arr1, np_arr2)): [ 1  2  3  4  5  6  7  8  9 10]
np.hstack((np_arr1, np_arr2)): [ 1  2  3  4  5  6  7  8  9 10]
np.vstack((np_arr1, np_arr2)): [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
my_numpy_arr = np.array([32, 3, 2, 4, 5, 5, 34, 34]).reshape(2, 2, 2)
print("my_numpy_arr:", my_numpy_arr)

my_numpy_arr: [[[32  3]
  [ 2  4]]

 [[ 5  5]
  [34 34]]]


In [9]:
np_arr = np.random.randint(10, 70, size=(5, 5))

In [10]:
print("np_arr:", np_arr)

np_arr: [[10 40 33 16 22]
 [60 25 14 52 58]
 [34 30 51 29 24]
 [61 58 12 66 37]
 [29 48 50 26 42]]


In [11]:
np_arr_flattened = np_arr.flatten()
print("np_arr_flattened:", np_arr_flattened)

np_arr_flattened: [10 40 33 16 22 60 25 14 52 58 34 30 51 29 24 61 58 12 66 37 29 48 50 26
 42]


In [12]:
np_arr_sorted = np.sort(np_arr)
# by default np sorting in ascending order
print("np_arr_sorted:", np_arr_sorted)
# to sort in descending order we can use
print("np_arr_sorted_descending:", np.sort(np_arr, axis=0)[::-1])
# or
print("np_arr_sorted_descending:", np.sort(np_arr, kind="mergesort"))
# [::-1] is used to reverse the sorted order, achieving descending sorting


# create a random 5x5 matrix
np_arr_rand = np.random.rand(5, 5)
print("np_arr_rand: 5*5", np_arr_rand)
# calculate the sum of all elements in the matrix
print("np_arr_rand.sum():", np_arr_rand.sum())
# calculate the mean of all elements in the matrix
print("np_arr_rand.mean():", np_arr_rand.mean())
# calculate the standard deviation of all elements in the matrix
print("np_arr_rand.std():", np_arr_rand.std())


# we can also do metrix operations using numpy
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])

np_arr_sorted: [[10 16 22 33 40]
 [14 25 52 58 60]
 [24 29 30 34 51]
 [12 37 58 61 66]
 [26 29 42 48 50]]
np_arr_sorted_descending: [[61 58 51 66 58]
 [60 48 50 52 42]
 [34 40 33 29 37]
 [29 30 14 26 24]
 [10 25 12 16 22]]
np_arr_sorted_descending: [[10 16 22 33 40]
 [14 25 52 58 60]
 [24 29 30 34 51]
 [12 37 58 61 66]
 [26 29 42 48 50]]
np_arr_rand: 5*5 [[0.20232765 0.18166347 0.52754859 0.65454203 0.05957995]
 [0.33200571 0.00842996 0.63163962 0.3690808  0.55909587]
 [0.66284597 0.67801348 0.09741751 0.42150249 0.43065693]
 [0.55325438 0.45762112 0.56192632 0.98655463 0.11319811]
 [0.14630752 0.47938204 0.39706634 0.18185689 0.30887738]]
np_arr_rand.sum(): 10.002394751738336
np_arr_rand.mean(): 0.40009579006953344
np_arr_rand.std(): 0.2338197832438188


In [13]:
# we can also do metrix operations using numpy
np_arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [2, 3, 4, 5]])
np_arr2 = np.array([[-1, 2.3, 3, 4], [-5, 6.7, 8, 9], [1, 2, 3, 4]])

# add two arrays
print("np_arr1 + np_arr2:", np_arr1 + np_arr2)
# subtract two arrays
print("np_arr1 - np_arr2:", np_arr1 - np_arr2)
# multiply two arrays
print("np_arr1 * np_arr2:", np_arr1 * np_arr2)
# divide two arrays
print("np_arr1 / np_arr2:", np_arr1 / np_arr2)

print("np_arr1:", np.array(np_arr1, dtype=np.float64))

np_arr1 + np_arr2: [[ 0.   4.3  6.   8. ]
 [ 0.  12.7 15.  17. ]
 [ 3.   5.   7.   9. ]]
np_arr1 - np_arr2: [[ 2.  -0.3  0.   0. ]
 [10.  -0.7 -1.  -1. ]
 [ 1.   1.   1.   1. ]]
np_arr1 * np_arr2: [[ -1.    4.6   9.   16. ]
 [-25.   40.2  56.   72. ]
 [  2.    6.   12.   20. ]]
np_arr1 / np_arr2: [[-1.          0.86956522  1.          1.        ]
 [-1.          0.89552239  0.875       0.88888889]
 [ 2.          1.5         1.33333333  1.25      ]]
np_arr1: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 3. 4. 5.]]


In [14]:
print("Number of axixes:", np_arr1.ndim)
print("Shape of array:", np_arr1.shape)
print("Size of array:", np_arr1.size)
print("Data type of array:", np_arr1.dtype)

Number of axixes: 2
Shape of array: (3, 4)
Size of array: 12
Data type of array: int64


In [15]:
print("Array's memory size:", np_arr1.nbytes)

print("np_arr1:", np.empty((3, 4)))

Array's memory size: 96
np_arr1: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 3. 4. 5.]]


In [16]:
print("ones array:", np.ones((10, 3)))
my_numpy_arr = np.linspace(0, 2.5, 20).reshape(2, 5, 2)
print("my_numpy_arr:", 10*np.sign(my_numpy_arr))

ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
my_numpy_arr: [[[ 0. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]]


In [17]:
print("array with predicated values:", np.linspace(0, 1, 6).reshape(3, 2, 1))

array with predicated values: [[[0. ]
  [0.2]]

 [[0.4]
  [0.6]]

 [[0.8]
  [1. ]]]


In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# matrix multiplication
print("Matrix multiplication of A and B:", A @ B)
print("using numpy multiply function:", np.matmul(A, B))
print("we can also use dot fun from numpy", np.dot(A, B))

# A*B - element-wise multiplication or product
# A-B - element-wise subtraction
# A+B - element-wise addition
# A/B - element-wise division
# A**2 - element-wise square

Matrix multiplication of A and B: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
using numpy multiply function: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
we can also use dot fun from numpy [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [19]:
# universal functions of numpy
# 1. exp() - exponential function
import numpy as np
B = np.arange(5, 10)
print("Matrix B:", B)
# exponential - calculates the exponential of each element in B
print("exp(B):", np.exp(B))
# log() - calculates the natural logarithm (base e) of each element in B
print("log(B):", np.log(B))
# sin() - calculates the sine of each element in B
print("sin(B):", np.sin(B))
# cos() - calculates the cosine of each element in B
print("cos(B):", np.cos(B))

Matrix B: [5 6 7 8 9]
exp(B): [ 148.4131591   403.42879349 1096.63315843 2980.95798704 8103.08392758]
log(B): [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
sin(B): [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
cos(B): [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]


In [20]:

random_arr = np.random.randint(1, int(np.pi), size=(3, 4))
print("Random 3x4 array with pi:", random_arr)

print("\n\n--------")
for row in random_arr:
    print(row)

Random 3x4 array with pi: [[2 1 1 2]
 [1 1 2 1]
 [1 2 1 1]]


--------
[2 1 1 2]
[1 1 2 1]
[1 2 1 1]


In [36]:
a=np.array([
    [
    [1,2,3,4,5],[6,7,8,9,10],[11,12,"13",14,5]]
    ],dtype=np.float32)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)
print(a.sum())

(1, 3, 5)
3
15
4
float32
60
110.0


In [69]:
arr_items = np.arange(1, 10, 0.3, dtype=np.float32)
print(arr_items)
# generate fix size of items 
arr_items=np.linspace(0,1,5)
print(arr_items)



[1.        1.3       1.5999999 1.8999999 2.1999998 2.4999998 2.7999997
 3.0999997 3.3999996 3.6999996 3.9999995 4.299999  4.5999994 4.8999996
 5.1999993 5.499999  5.799999  6.0999994 6.399999  6.699999  6.999999
 7.299999  7.599999  7.8999987 8.199999  8.499999  8.799999  9.099998
 9.399999  9.699999 ]
[0.   0.25 0.5  0.75 1.  ]


In [83]:
nan_value=np.nan
np_inf=np.inf
print(nan_value)
print(np_inf)
# check the type of the nan value
print(type(nan_value))
print(type(np_inf))
# check if the value is NaN
print(np.isnan(nan_value))
# check if the value is infinity
print(np.isinf(np_inf))

# create a 3x3 identity matrix
np_identity_matrix=np.eye(3)
print(np_identity_matrix)

nan
inf
<class 'float'>
<class 'float'>
True
True
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [130]:
np_arr=np.array([1,2,3,4,5,6,7,8,9])

# insert the items 
np_arr1=np.insert(np_arr,3,[10,11,12])
print(np_arr1)
print(np_arr)

# update the items 
np_arr2=np.array([1,2,3,4,5,6,7,8,9,10])
np_arr2[3:6]=[100,200,300]
print(np_arr2)

# delete the items
np_arr3=np.delete(np_arr2,[3,5])
print(np_arr3)
print("---------")
np_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np_arr)
print("delete the first column",np.delete(np_arr,[0,2],axis=1))

[ 1  2  3 10 11 12  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]
[  1   2   3 100 200 300   7   8   9  10]
[  1   2   3 200   7   8   9  10]
---------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
delete the first column [[ 2  4]
 [ 6  8]
 [10 12]]


In [232]:
# print(np.eye(5,3,dtype=np.uint16))
print(np.diag([1, 2, 3,5,4],0)
)
np.linspace(0, 2, 20).reshape(2,5,2)
# (2,5,2) - means 2x5x2 matrices


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 4]]


array([[[0.        , 0.10526316],
        [0.21052632, 0.31578947],
        [0.42105263, 0.52631579],
        [0.63157895, 0.73684211],
        [0.84210526, 0.94736842]],

       [[1.05263158, 1.15789474],
        [1.26315789, 1.36842105],
        [1.47368421, 1.57894737],
        [1.68421053, 1.78947368],
        [1.89473684, 2.        ]]])

In [273]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])

# access the items
print(A[0]) # prints the first row
print(A[0][0]) # prints the first element of the first row
print(A[:,0]) # prints the first column
print(A[0:2,0:2]) # prints the first two rows and first two columns
# get fist column
print(A[:,0])
print(A[:,1]) # get second column

# print the all even numbers in the matrix
print(A[A % 2 == 0])
# or 
even_items=np.where(A % 2 == 0)
print(A[even_items])

search_index=[1,2]
print(A,"-----")
print(A[search_index])

[1 2 3]
1
[1 4 7]
[[1 2]
 [4 5]]
[1 4 7]
[2 5 8]
[2 4 6 8]
[2 4 6 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]] -----
[[4 5 6]
 [7 8 9]]
