In [268]:
import numpy as np


def generate_random_numbers(size, min_val, max_val):
    return np.random.randint(min_val, max_val, size)


random_numbers = generate_random_numbers(50, 1, 1777700)
print(random_numbers)
# python array
python_arr = [1, 3, 4, 5]
# convert to numpy array
numpy_arr = np.array(python_arr)
print(numpy_arr)
print(type(numpy_arr))

[ 305120 1639822 1418756  901538  393918 1266089  456968  801301 1117313
 1359976  949268  655523  284667 1299328 1002956  727701  552301 1697108
  628725  601937 1736096  629817  792635  634896  688966 1275211 1415914
  303518 1434706  192525 1095010  231998  242793   55746  856111  267255
 1762213  430597 1391879  643824  415682  705525  899220   42091 1349654
  426451   45919  218534 1553920 1738897]
[1 3 4 5]
<class 'numpy.ndarray'>


In [269]:

# numpy array operations
numpy_arr_2 = np.array([1, 2, 3, 4, 5])
print("numpy_arr_2:", numpy_arr_2)
print("numpy_arr_2 + 2:", numpy_arr_2 + 2)
print("numpy_arr_2 * 2:", numpy_arr_2 * 2)
print("numpy_arr_2 / 2:", numpy_arr_2 / 2)
print("numpy_arr_2 ** 2:", numpy_arr_2 ** 2)
print("numpy_arr_2.sum():", numpy_arr_2.sum())

numpy_arr_2: [1 2 3 4 5]
numpy_arr_2 + 2: [3 4 5 6 7]
numpy_arr_2 * 2: [ 2  4  6  8 10]
numpy_arr_2 / 2: [0.5 1.  1.5 2.  2.5]
numpy_arr_2 ** 2: [ 1  4  9 16 25]
numpy_arr_2.sum(): 15


In [270]:
print("numpy_arr_2.mean():", numpy_arr_2.mean())
print("numpy_arr_2.std():", numpy_arr_2.std())

numpy_arr_2.mean(): 3.0
numpy_arr_2.std(): 1.4142135623730951


In [271]:
import time

python_2d_arr = [[1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6], [1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6,
                                                                                                                                                              6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6], [1, 2, 3, 3, 4, 5, 5, 65, 6, 6, 76, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 66, 6, 6, 6]]
start_python_time = time.time()
python_2d_arr_sum = sum([sum(row) for row in python_2d_arr])
end_python_time = time.time()
print("Python 2D array sum:", python_2d_arr_sum,
      " total time taken:", end_python_time-start_python_time)

# lets do the same with numpy
numpy_2d_arr = np.array(python_2d_arr)
start_numpy_time = time.time()
numpy_2d_arr_sum = numpy_2d_arr.sum()
end_numpy_time = time.time()
print("Numpy 2D array sum:", numpy_2d_arr_sum,
      " total time taken:", end_numpy_time-start_numpy_time)

Python 2D array sum: 1320  total time taken: 5.817413330078125e-05
Numpy 2D array sum: 1320  total time taken: 5.5789947509765625e-05


In [272]:
numpy_arr_2 = np.array([1, 2, 3, 4, 5, 6])
print("numpy_arr_2:", numpy_arr_2)
# shape method - returns the dimensions of the array as a tuple
print("numpy_arr_2.shape:", numpy_arr_2.shape)
numpy_2d_arr_3x3 = np.random.randint(1, 11, size=(4, 4))
print("numpy_2d_arr_3x3:", numpy_2d_arr_3x3)
"""
reshape()- returns a new array with the specified shape.
input parameters:
- newshape: a tuple of integers defining the new shape.
   - eg, (2,3)- the array will be reshaped to a 2x3 array.
   - 3g (2,3,4)- the array will be reshaped to a 2x3x4 array.
- (t1,t12,t3,t4)
   """
print("numpy_2d_arr_3x3m-reshape ----", numpy_2d_arr_3x3.shape,
      numpy_2d_arr_3x3.reshape(4, 2, 2), "-----")

# get the maximum value in the array
print("numpy_2d_arr_3x3.max():", numpy_2d_arr_3x3.max())
# get the minimum value in the array
print("numpy_2d_arr_3x3.min():", numpy_2d_arr_3x3.shape, numpy_2d_arr_3x3.min())

# retrun all element as array or flatted array
# print("numpy_2d_arr_3x3.flatten():",numpy_2d_arr_3x3.flatten())
# reshape the array
# print("numpy_2d_arr_3x3.reshape(4,16):",numpy_2d_arr_3x3.reshape(4,16))
# print(numpy_2d_arr_3x3)

# type of numpy array
print(type(numpy_2d_arr_3x3), "items types", numpy_2d_arr_3x3.dtype)
# cast the all items to float/anything
print("numpy_2d_arr_3x3.astype(float):", numpy_2d_arr_3x3.astype(float))

numpy_arr_2: [1 2 3 4 5 6]
numpy_arr_2.shape: (6,)
numpy_2d_arr_3x3: [[ 9  8  7  6]
 [ 6  3  6  1]
 [ 6  7  8  3]
 [10  5  7  9]]
numpy_2d_arr_3x3m-reshape ---- (4, 4) [[[ 9  8]
  [ 7  6]]

 [[ 6  3]
  [ 6  1]]

 [[ 6  7]
  [ 8  3]]

 [[10  5]
  [ 7  9]]] -----
numpy_2d_arr_3x3.max(): 10
numpy_2d_arr_3x3.min(): (4, 4) 1
<class 'numpy.ndarray'> items types int64
numpy_2d_arr_3x3.astype(float): [[ 9.  8.  7.  6.]
 [ 6.  3.  6.  1.]
 [ 6.  7.  8.  3.]
 [10.  5.  7.  9.]]


In [273]:
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])
# merge two arrays
print("np.concatenate((np_arr1, np_arr2)):",
      np.concatenate((np_arr1, np_arr2)))
# other way to merge two arrays
print("np.hstack((np_arr1, np_arr2)):", np.hstack((np_arr1, np_arr2)))
print("np.vstack((np_arr1, np_arr2)):", np.vstack((np_arr1, np_arr2)))

np.concatenate((np_arr1, np_arr2)): [ 1  2  3  4  5  6  7  8  9 10]
np.hstack((np_arr1, np_arr2)): [ 1  2  3  4  5  6  7  8  9 10]
np.vstack((np_arr1, np_arr2)): [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [274]:
my_numpy_arr = np.array([32, 3, 2, 4, 5, 5, 34, 34]).reshape(2, 2, 2)
print("my_numpy_arr:", my_numpy_arr)

my_numpy_arr: [[[32  3]
  [ 2  4]]

 [[ 5  5]
  [34 34]]]


In [275]:
np_arr = np.random.randint(10, 70, size=(5, 5))

In [276]:
print("np_arr:", np_arr)

np_arr: [[69 47 10 68 41]
 [39 33 15 28 51]
 [26 43 38 25 64]
 [61 53 40 64 49]
 [21 37 23 36 26]]


In [277]:
np_arr_flattened = np_arr.flatten()
print("np_arr_flattened:", np_arr_flattened)

np_arr_flattened: [69 47 10 68 41 39 33 15 28 51 26 43 38 25 64 61 53 40 64 49 21 37 23 36
 26]


In [278]:
np_arr_sorted = np.sort(np_arr)
# by default np sorting in ascending order
print("np_arr_sorted:", np_arr_sorted)
# to sort in descending order we can use
print("np_arr_sorted_descending:", np.sort(np_arr, axis=0)[::-1])
# or
print("np_arr_sorted_descending:", np.sort(np_arr, kind="mergesort"))
# [::-1] is used to reverse the sorted order, achieving descending sorting


# create a random 5x5 matrix
np_arr_rand = np.random.rand(5, 5)
print("np_arr_rand: 5*5", np_arr_rand)
# calculate the sum of all elements in the matrix
print("np_arr_rand.sum():", np_arr_rand.sum())
# calculate the mean of all elements in the matrix
print("np_arr_rand.mean():", np_arr_rand.mean())
# calculate the standard deviation of all elements in the matrix
print("np_arr_rand.std():", np_arr_rand.std())


# we can also do metrix operations using numpy
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])

np_arr_sorted: [[10 41 47 68 69]
 [15 28 33 39 51]
 [25 26 38 43 64]
 [40 49 53 61 64]
 [21 23 26 36 37]]
np_arr_sorted_descending: [[69 53 40 68 64]
 [61 47 38 64 51]
 [39 43 23 36 49]
 [26 37 15 28 41]
 [21 33 10 25 26]]
np_arr_sorted_descending: [[10 41 47 68 69]
 [15 28 33 39 51]
 [25 26 38 43 64]
 [40 49 53 61 64]
 [21 23 26 36 37]]
np_arr_rand: 5*5 [[0.63228045 0.11392729 0.71958616 0.61434707 0.42909353]
 [0.81750024 0.29313939 0.95937711 0.10546651 0.36891291]
 [0.02982005 0.72480865 0.94665333 0.04694854 0.93280523]
 [0.88411375 0.581617   0.35286873 0.37421294 0.14760063]
 [0.56525506 0.5236938  0.00126816 0.19986331 0.22848423]]
np_arr_rand.sum(): 11.593644057239224
np_arr_rand.mean(): 0.463745762289569
np_arr_rand.std(): 0.3049181428894023


In [279]:
# we can also do metrix operations using numpy
np_arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [2, 3, 4, 5]])
np_arr2 = np.array([[-1, 2.3, 3, 4], [-5, 6.7, 8, 9], [1, 2, 3, 4]])

# add two arrays
print("np_arr1 + np_arr2:", np_arr1 + np_arr2)
# subtract two arrays
print("np_arr1 - np_arr2:", np_arr1 - np_arr2)
# multiply two arrays
print("np_arr1 * np_arr2:", np_arr1 * np_arr2)
# divide two arrays
print("np_arr1 / np_arr2:", np_arr1 / np_arr2)

print("np_arr1:", np.array(np_arr1, dtype=np.float64))

np_arr1 + np_arr2: [[ 0.   4.3  6.   8. ]
 [ 0.  12.7 15.  17. ]
 [ 3.   5.   7.   9. ]]
np_arr1 - np_arr2: [[ 2.  -0.3  0.   0. ]
 [10.  -0.7 -1.  -1. ]
 [ 1.   1.   1.   1. ]]
np_arr1 * np_arr2: [[ -1.    4.6   9.   16. ]
 [-25.   40.2  56.   72. ]
 [  2.    6.   12.   20. ]]
np_arr1 / np_arr2: [[-1.          0.86956522  1.          1.        ]
 [-1.          0.89552239  0.875       0.88888889]
 [ 2.          1.5         1.33333333  1.25      ]]
np_arr1: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 3. 4. 5.]]


In [280]:
print("Number of axixes:", np_arr1.ndim)
print("Shape of array:", np_arr1.shape)
print("Size of array:", np_arr1.size)
print("Data type of array:", np_arr1.dtype)

Number of axixes: 2
Shape of array: (3, 4)
Size of array: 12
Data type of array: int64


In [281]:
print("Array's memory size:", np_arr1.nbytes)

print("np_arr1:", np.empty((3, 4)))

Array's memory size: 96
np_arr1: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [2. 3. 4. 5.]]


In [282]:
print("ones array:", np.ones((10, 3)))
my_numpy_arr = np.linspace(0, 2.5, 20).reshape(2, 5, 2)
print("my_numpy_arr:", 10*np.sign(my_numpy_arr))

ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
my_numpy_arr: [[[ 0. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]
  [10. 10.]]]


In [283]:
print("array with predicated values:", np.linspace(0, 1, 6).reshape(3, 2, 1))

array with predicated values: [[[0. ]
  [0.2]]

 [[0.4]
  [0.6]]

 [[0.8]
  [1. ]]]


In [284]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# matrix multiplication
print("Matrix multiplication of A and B:", A @ B)
print("using numpy multiply function:", np.matmul(A, B))
print("we can also use dot fun from numpy", np.dot(A, B))

# A*B - element-wise multiplication or product
# A-B - element-wise subtraction
# A+B - element-wise addition
# A/B - element-wise division
# A**2 - element-wise square

Matrix multiplication of A and B: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
using numpy multiply function: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
we can also use dot fun from numpy [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [285]:
# universal functions of numpy
# 1. exp() - exponential function
import numpy as np
B = np.arange(5, 10)
print("Matrix B:", B)
# exponential - calculates the exponential of each element in B
print("exp(B):", np.exp(B))
# log() - calculates the natural logarithm (base e) of each element in B
print("log(B):", np.log(B))
# sin() - calculates the sine of each element in B
print("sin(B):", np.sin(B))
# cos() - calculates the cosine of each element in B
print("cos(B):", np.cos(B))

Matrix B: [5 6 7 8 9]
exp(B): [ 148.4131591   403.42879349 1096.63315843 2980.95798704 8103.08392758]
log(B): [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
sin(B): [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
cos(B): [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]


In [286]:

random_arr = np.random.randint(1, int(np.pi), size=(3, 4))
print("Random 3x4 array with pi:", random_arr)

print("\n\n--------")
for row in random_arr:
    print(row)

Random 3x4 array with pi: [[2 1 2 2]
 [2 1 2 2]
 [1 2 1 1]]


--------
[2 1 2 2]
[2 1 2 2]
[1 2 1 1]


In [287]:
a = np.array([
    [
        [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, "13", 14, 5]]
], dtype=np.float32)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)
print(a.sum())

(1, 3, 5)
3
15
4
float32
60
110.0


In [288]:
arr_items = np.arange(1, 10, 0.3, dtype=np.float32)
print(arr_items)
# generate fix size of items
arr_items = np.linspace(0, 1, 5)
print(arr_items)

[1.        1.3       1.5999999 1.8999999 2.1999998 2.4999998 2.7999997
 3.0999997 3.3999996 3.6999996 3.9999995 4.299999  4.5999994 4.8999996
 5.1999993 5.499999  5.799999  6.0999994 6.399999  6.699999  6.999999
 7.299999  7.599999  7.8999987 8.199999  8.499999  8.799999  9.099998
 9.399999  9.699999 ]
[0.   0.25 0.5  0.75 1.  ]


In [289]:
nan_value = np.nan
np_inf = np.inf
print(nan_value)
print(np_inf)
# check the type of the nan value
print(type(nan_value))
print(type(np_inf))
# check if the value is NaN
print(np.isnan(nan_value))
# check if the value is infinity
print(np.isinf(np_inf))

# create a 3x3 identity matrix
np_identity_matrix = np.eye(3)
print(np_identity_matrix)

nan
inf
<class 'float'>
<class 'float'>
True
True
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [290]:
np_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# insert the items
np_arr1 = np.insert(np_arr, 3, [10, 11, 12])
print(np_arr1)
print(np_arr)

# update the items
np_arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_arr2[3:6] = [100, 200, 300]
print(np_arr2)

# delete the items
np_arr3 = np.delete(np_arr2, [3, 5])
print(np_arr3)
print("---------")
np_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np_arr)
print("delete the first column", np.delete(np_arr, [0, 2], axis=1))

[ 1  2  3 10 11 12  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]
[  1   2   3 100 200 300   7   8   9  10]
[  1   2   3 200   7   8   9  10]
---------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
delete the first column [[ 2  4]
 [ 6  8]
 [10 12]]


In [291]:
# print(np.eye(5,3,dtype=np.uint16))
print(np.diag([1, 2, 3, 5, 4], 0)
      )
np.linspace(0, 2, 20).reshape(2, 5, 2)
# (2,5,2) - means 2x5x2 matrices

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 4]]


array([[[0.        , 0.10526316],
        [0.21052632, 0.31578947],
        [0.42105263, 0.52631579],
        [0.63157895, 0.73684211],
        [0.84210526, 0.94736842]],

       [[1.05263158, 1.15789474],
        [1.26315789, 1.36842105],
        [1.47368421, 1.57894737],
        [1.68421053, 1.78947368],
        [1.89473684, 2.        ]]])

In [292]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# access the items
print(A[0])  # prints the first row
print(A[0][0])  # prints the first element of the first row
print(A[:, 0])  # prints the first column
print(A[0:2, 0:2])  # prints the first two rows and first two columns
# get fist column
print(A[:, 0])
print(A[:, 1])  # get second column

# print the all even numbers in the matrix
print(A[A % 2 == 0])
# or
even_items = np.where(A % 2 == 0)
print(A[even_items])

search_index = [1, 2]
print(A, "-----")
print(A[search_index])

[1 2 3]
1
[1 4 7]
[[1 2]
 [4 5]]
[1 4 7]
[2 5 8]
[2 4 6 8]
[2 4 6 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]] -----
[[4 5 6]
 [7 8 9]]


In [293]:
# 0-D array or Scalars is treated as a single element
zero_d_array = np.random.randint(1, 20, 20).reshape(5, 4)
print(zero_d_array)

[[ 8 14 12  2]
 [10 17 15  5]
 [ 1  8  7  7]
 [ 5  8 13 12]
 [11  6  8  4]]


In [294]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])
print(arr[::-1])

a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

for i1, i2 in zip(a1, a2):
    print(i1, "+", i2, "=", i1+i2)

50
[50 40 30 20 10]
1 + 6 = 7
2 + 7 = 9
3 + 8 = 11
4 + 9 = 13
5 + 10 = 15


In [295]:
a3 = np.array([1, 2, 3, 4, 5])
a4 = np.array([6, 7, 8, 9, 10])

result = np.stack((a3, a4))
print(result,"stack array")

result = np.vstack((a3, a4))
print(result,"vertical stack array")
result = np.concatenate( (a3, a4))
print(result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] stack array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] vertical stack array
[ 1  2  3  4  5  6  7  8  9 10]


In [296]:
a=np.array([1, 2, 3, 4, 5])
print(a[2:3])
print(a[2:])
str=np.array(['apple', 'bananaa', 'cherry'])
print(a.dtype)
print(str.dtype)

[3]
[3 4 5]
int64
<U7


In [297]:
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""
print(a.itemsize)
print(str.itemsize)
print(a.nbytes)
print(str.nbytes)
print(a.ndim)
print(str.ndim)

custom_arr=np.array([1,3,4],dtype="S")
print(custom_arr.dtype)
print(custom_arr.itemsize)
print(custom_arr.nbytes)
print(custom_arr.ndim)

arr = np.array([1, 0, 3])
new_arr=arr.astype(bool)
print(new_arr,"==",new_arr.dtype)


8
28
40
84
1
1
|S1
1
3
1
[ True False  True] == bool


In [298]:
arr = np.array([1, 2, 3, 4, 5])
# create copy 
arr_cp=arr.copy()
arr_cp[0]=100
print("Copy Method","Original Array:",arr , "COPY Array:",arr_cp)

arr_view=arr.view()
arr_view[0]=100
print("View Method","Original Array:",arr , "VIEW Array:",arr_view)
# in short copy allows to create fresh new arr where all initial items are copied  from original array
# while view allows to create new arr where changes in original array will reflect in new array
# copy - owns the data whike view - does not
# we can check 
print("arr_cp own the data",arr_cp.base is arr)
print("arr_view own the data",arr_view.base is arr)

Copy Method Original Array: [1 2 3 4 5] COPY Array: [100   2   3   4   5]
View Method Original Array: [100   2   3   4   5] VIEW Array: [100   2   3   4   5]
arr_cp own the data False
arr_view own the data True


In [299]:
arr = np.array([[[1, 2,3],[3, 4,33]], [[5, 6,3], [333,7, 8]]])
print(arr.shape)
print(arr.ndim)

(2, 2, 3)
3


In [300]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

# [[[1,2],[..],[..]],[[..],[..],[..]]]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [301]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4,-1))
print(arr.copy())

multi_arr=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(multi_arr.reshape(-1))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]
[1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [302]:
# iterating over multi-dimensional array
for x in multi_arr:
    print(x,type(x))  


print("---------")
# iterate over each element in multi-dimensional array in reverse order
for row in multi_arr:
    for col in row:
        for element in col:
            print(element, end=" ")


print("\n---------")
# using nditer 
for element in np.nditer(np.array([1, 2, 3])
,flags=["buffered"],op_dtypes=["S"]):
    print(element)

print("\n---------")


# using ndenumerate
for index, value in np.ndenumerate(multi_arr):
    print(index, value)

print("\n---------")


[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'>
---------
1 2 3 4 5 6 7 8 9 10 11 12 
---------
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')

---------
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12

---------


In [303]:
# using ndindex
for index in np.ndindex(multi_arr.shape):
    print(index)

print("\n---------")

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)
(1, 0, 0)
(1, 0, 1)
(1, 0, 2)
(1, 1, 0)
(1, 1, 1)
(1, 1, 2)

---------


In [304]:
arr1 = np.array([[22,221], [233, 464]])

arr2 = np.array([[1, 63], [12, 3]])

arr = np.concatenate((arr1, arr2), axis=1)
arr_row= np.concatenate((arr1, arr2), axis=0)
print("nd array concatenate along axis 0",arr_row)
print("nd array concatenate along axis 1",arr)

nd array concatenate along axis 0 [[ 22 221]
 [233 464]
 [  1  63]
 [ 12   3]]
nd array concatenate along axis 1 [[ 22 221   1  63]
 [233 464  12   3]]


In [305]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
# if we do the horizontal  stack - all elements of arr1 
# will be in the first row and all elements of arr2 will be in the second row
print("arr - ",arr)
arr=np.vstack((arr1, arr2))
print("arr - ",arr)

arr -  [1 2 3 4 5 6]
arr -  [[1 2 3]
 [4 5 6]]


In [306]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,4)

print(newarr)

# array_split will manage the split sizes automatically 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.array_split(arr,4))
newarr = np.split(arr, 3)
print("new_arr[0]",newarr[0])
for arr in newarr:
    print(arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([], shape=(0, 3), dtype=int64)]
new_arr[0] [[1 2 3]]
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [307]:
arr = np.array([15, 38, 41, 46])
# wehre function returns the indices of elements that satisfy the condition
x = np.where(arr%2 == 1)
print(x)
print(arr[x])

arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x=np.where(arr>5)
print(x[0])
print(arr[x])

(array([0, 2]),)
[15 41]
[5 6 7 8 9]
[ 6  7  8  9 10]


In [308]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x=np.searchsorted(arr, 5)
insert_postion=x
value_to_insert=5
arr = np.insert(arr,insert_postion,value_to_insert)
print(arr)
# we can controll the search direction 
x=np.searchsorted(arr, 5, side='right')
print(x)

# we can search for multiple values
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x=np.searchsorted(arr, [5, 15, 25])
print(x)

# insert multiple values
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
values_to_insert=[100, 200, 300]
insert_postions=[3, 7, 9]
arr = np.insert(arr, insert_postions, values_to_insert)
print(arr)

[ 1  2  3  4  5  5  6  7  8  9 10]
6
[ 4 10 10]
[  1   2   3 100   4   5   6   7 200   8   9 300  10]


In [309]:
sorted_arr=np.sort(arr)[::-1]
print("sorted_arr",sorted_arr)

# boolean arr
arr = np.array([True, False, True, False])
print("Boolean array:",np.sort(arr))
print(arr.any())
print(arr.all())

string_arr=["A","B","Cat","Dog","Elephant"]
print(np.sort(string_arr)[::-1])

arr = np.array([[3, 2, 4], [9, 8, 7], [6, 5, 1]])
print("Sorted array:", np.sort(arr, axis=1)[::-1])

sorted_arr [300 200 100  10   9   8   7   6   5   4   3   2   1]
Boolean array: [False False  True  True]
True
False
['Elephant' 'Dog' 'Cat' 'B' 'A']
Sorted array: [[1 5 6]
 [7 8 9]
 [2 3 4]]


In [310]:
# filtering the array items
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
filtered_arr = arr[arr % 2 == 1]
print("Filtered array:", filtered_arr)

bool_arr = np.array([True, False, True, False,True, False, True, False, True, False])
filtered_bool_arr = arr[bool_arr]
print("Filtered based on boolean arr:", filtered_bool_arr)

Filtered array: [1 3 5 7 9]
Filtered based on boolean arr: [1 3 5 7 9]


In [311]:
filter_bool_arr = []

for items in arr:
    if items % 2 == 1:
        filter_bool_arr.append(True)
    else:
        filter_bool_arr.append(False)

print(filter_bool_arr)

filtered_arr = arr[filter_bool_arr]
print("Filtered based on boolean list:", filtered_arr)

[True, False, True, False, True, False, True, False, True, False]
Filtered based on boolean list: [1 3 5 7 9]
