In [4]:
import numpy as np
import pandas as pd


In [5]:
x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]
z = []
for i, j in zip(x, y):
    print(f"The value - [{i+j}]")
    z.append(i+j)
print("after add operation:", z)
# Using numpy arrays
x_np = np.array(x)
y_np = np.array(y)
print("----using numpy arrays----")
print(f"The numpy array values - [{np.add(x_np, y_np)}]")


The value - [11]
The value - [22]
The value - [33]
The value - [44]
The value - [55]
after add operation: [11, 22, 33, 44, 55]
----using numpy arrays----
The numpy array values - [[11 22 33 44 55]]


In [ ]:
def myAdd(x, y):
    return x+y


myAddFunc = np.frompyfunc(myAdd, 2, 1)

print("----using numpy frompyfunc----")
print(f"The numpy frompyfunc values - {myAddFunc(x, y)}")

substraction_np = np.subtract(x_np, y_np)
print("after subtraction operation:", substraction_np)
devision_np = np.divide(x_np, y_np)
print("after division operation:", devision_np)
remainder_np = np.mod(x_np, y_np)
print("after remainder operation:", remainder_np)
# divmode() returns a tuple (quotient, remainder) so it returns both quotient and remainder
# (x//y, x%y) = np.divmod(x_np, y_np)'
print("after divmod operation:", np.divmod(x_np, y_np))
# getting abosulte values
abs_np = np.abs(x_np)
print("after absolute operation:", abs_np)
# type checking
print("----type checking----")
print(f"The type of myAddFunc - {type(myAddFunc)}")
print(f"The type of np.add - {type(np.add)}")
print(f"The type of np.concatenate - {type(np.concatenate)}")


----using numpy frompyfunc----
The numpy frompyfunc values - [11 22 33 44 55]
after subtraction operation: [ -9 -18 -27 -36 -45]
after division operation: [0.1 0.1 0.1 0.1 0.1]
after remainder operation: [1 2 3 4 5]
after divmod operation: (array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))
after absolute operation: [1 2 3 4 5]
----type checking----
The type of myAddFunc - <class 'numpy.ufunc'>
The type of np.add - <class 'numpy.ufunc'>
The type of np.concatenate - <class 'numpy._ArrayFunctionDispatcher'>


In [7]:
# Rounding Decimals - numpy
print("----rounding decimals----")
# around- it increments the nearest number by 1 if the decimal part is 0.5 or more else it takes the integer part.
print(f"Rounded values - {np.around([1.599, 2.93389, 3.5, 1])}")
# floor - it rounds off to the nearest integer.
# in case of negative numbers, it rounds down to the nearest integer. eg: floor(-1.5) = -2, floor(-3.5) = -4
print(f"Floor values - {np.floor([1.599, 2.99999, 3.5, 1, -3.999, -3.22])}")
# ceil - it rounds up to the nearest integer.
print(f"Ceil values - {np.ceil([1.599, 2.99999, 3.5, 1, -3.9])}")

# truncate or fix function - numpy
# it removes the decimal part from the number.and return the floating part
print("----truncate or fix function----")
print(
    f"Truncated values - {np.trunc([1.599, 2.99999, 3.5, 1, -3.999, -3.22])}")
print(f"fix values - {np.fix([1.599, 2.99999, 3.5, 1, -3.999, -3.22])}")


----rounding decimals----
Rounded values - [2. 3. 4. 1.]
Floor values - [ 1.  2.  3.  1. -4. -4.]
Ceil values - [ 2.  3.  4.  1. -3.]
----truncate or fix function----
Truncated values - [ 1.  2.  3.  1. -3. -3.]
fix values - [ 1.  2.  3.  1. -3. -3.]


In [57]:
# numpy Logs -
# numpy provide log with base 2 ,e ,10
import math

arr = np.arange(1, 10)
print("----numpy logs----", arr, "\n")
print(f"Log base 2 values - {np.log2(arr)}")
print(f"Log base e values - {np.log(arr)}")
print(f"Log base 10 values - {np.log10(arr)}")
print(f"Natural logarithm values or  base e  - {np.log(arr)}")

# we can perform the log with any base using np.log(base, arr)
np_log = np.frompyfunc(math.log, 2, 1)
print(f"Log base 15 values - {np_log(122, 22)}")

print(f"Natural logarithm values with invalid value - {np.log((-1))}")


----numpy logs---- [1 2 3 4 5 6 7 8 9] 

Log base 2 values - [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
Log base e values - [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
Log base 10 values - [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
Natural logarithm values or  base e  - [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
Log base 15 values - 1.5541750452226386
Natural logarithm values with invalid value - nan


/var/folders/bh/4rclxbnx2016p9vvx1sx17th0000gn/T/ipykernel_17412/3531510506.py:16: RuntimeWarning: invalid value encountered in log
  print(f"Natural logarithm values with invalid value - {np.log((-1))}")


In [138]:
print(f"we can peform the add on diff axis {np.add(x_np, y_np)}")

print(f"we can get total sum of elements by  {np.sum([x_np, y_np])}")
print(f"we can get the sum on axis-0 {np.sum([x_np, y_np], axis=0)}")
print(f"we can get the sum on axis-1 {np.sum([x_np, y_np], axis=1)}")

# commulative sum
x_np = np.array([1, 2, 3, 4, 5])
y_np = np.array([10, 20, 30, 40, 50])
print(f"Original array cummulative sum {np.cumsum(x_np)}")
print(f"Commulative sum along axis 0 {np.cumsum([x_np, y_np], axis=0)}")
print(f"Commulative sum along axis 1 {np.cumsum([x_np, y_np], axis=1)}")


we can peform the add on diff axis [11 22 33 44 55]
we can get total sum of elements by  165
we can get the sum on axis-0 [11 22 33 44 55]
we can get the sum on axis-1 [ 15 150]
Original array cummulative sum [ 1  3  6 10 15]
Commulative sum along axis 0 [[ 1  2  3  4  5]
 [11 22 33 44 55]]
Commulative sum along axis 1 [[  1   3   6  10  15]
 [ 10  30  60 100 150]]


In [181]:
# numpy products
x_np = np.array([1, 2, 3, 4, 5])
y_np = np.array([10, 20, 30, 40, 50])
print(f"product on flatted array {np.prod([x_np, y_np])}")
print(f"orginal array product {np.cumprod(x_np)}")
print(f"product along axis 0 {np.prod([x_np, y_np], axis=0)}")
print(f"product along axis 1 {np.prod([x_np, y_np], axis=1)}")
print(f"product along axis -1 {np.prod([x_np, y_np], axis=-1)}")
# axis=0 means across vertically
# axis 1 means operates horizontally
# axis -1 means operates horizontally in reverse order

new_arr = np.cumprod(x_np)
new_arr


product on flatted array 1440000000
orginal array product [  1   2   6  24 120]
product along axis 0 [ 10  40  90 160 250]
product along axis 1 [     120 12000000]
product along axis -1 [     120 12000000]


array([  1,   2,   6,  24, 120])

In [189]:
# diffrence fun
print(f"x_np array", x_np)
# b-a,c-b,d-c,e-d,....so on.
print(f"diffrence on original array  {np.diff(x_np)}")
# diffrence along axis 0 - vertically x-a,y-b,z-c,....so on.
print(f"diffrence along axis 0 {np.diff([x_np, y_np], axis=0)}")
# diffrence along axis 1 - horizontally [[b-a,c-b,...],[y-x,z-y]]so on.
print(f"diffrence along axis 1 {np.diff([x_np, y_np], axis=1)}")
# we can pass the count/num_of_times operatiion needs to perform in diffrence function
    


x_np array [1 2 3 4 5]
diffrence on original array  [1 1 1 1]
diffrence along axis 0 [[ 9 18 27 36 45]]
diffrence along axis 1 [[ 1  1  1  1]
 [10 10 10 10]]
